---
require:
  - rubocop-rspec
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/beaker-gke.rb'

Security/Eval:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false
