---
require:
  - rubocop-rspec
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: 20
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
