language: ruby
sudo: false
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  - gem update --system && gem install bundler --no-document
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false

matrix:
  include:
    - rvm: 2.5
      env: "CHECK=rubocop"

    - rvm: 2.5
      env: "CHECK=test:spec:run"