---
:apiVersion: v1
:kind: Pod
:metadata:
  :name: "%{pod_name}"
  :namespace: gke-puppetagent-ci
  :labels:
    :app: "%{pod_name}"
:spec:
  :hostname: "%{pod_name}"
  :containers:
    - :image: gcr.io/puppetagent-ci/centos-7:v5
      :name: "centos-7"
  :dnsPolicy: "None"
  :dnsConfig:
    nameservers:
      - 10.240.0.10
      - 10.240.1.10
    :searches:
      - gke-puppetagent-ci.puppet.net
  :hostAliases:
    - :ip: "169.254.169.254"
      :hostnames:
        - "metadata.google.internal"
