---
:apiVersion: v1
:kind: Service
:metadata:
  :name: "%{pod_name}"
  :namespace: gke-puppetagent-ci
  :labels:
    :app: "%{pod_name}"
:spec:
  :selector:
    :app: "%{pod_name}"
  :clusterIP: "None"
